### PR TITLE
Windows Mobile 10 - Close button does not work, this fixes #196

### LINKED ISSUE #196: Windows Mobile 10 - Close button does not work
The title explains it: When testing on Windows Mobile 10, the barcode scanner loads, but clicking on Close doesn't do anything.
Clicking Back closes the app, after that the camera driver has crashed, causing a green screen...

### PR DESCRIPTION
**Pull request by daserge**
Introduced `scanCancelled` flag to handle the cancelled state.
More proper way to fix this is to cancel the scan promise chain, but it's causing `NotFoundError` in `Windows.Devices.Enumeration.DeviceInformation.findAllAsync` for some reason.

### CODE REVIEW

File: src/windows/BarcodeScannerProxy.js [hunk 1]
```diff
@@ -432,21 +432,39 @@ module.exports = {
...
+            if (BarcodeReader.scanCancelled) {
+                throw new Error('Canceled');
+            }
+        }
+
+        if (BarcodeReader.scanCancelled) {
+            success({
+                cancelled: true
+            });
+            BarcodeReader.scanCancelled = false;
```
Comment (vladimir-kotikov) [inline src/windows/BarcodeScannerProxy.js]: Probably it's more convenient to set this to `false` in `createPreview` once - just before binding `cancelPreview` to back and Cancel buttons

File: src/windows/BarcodeScannerProxy.js [hunk 2]
```diff
@@ -457,9 +475,20 @@ module.exports = {
                 format: result && BARCODE_FORMAT[result.barcodeFormat],
                 cancelled: !result
             });
+
+            BarcodeReader.scanCancelled = false;
```
Comment (vladimir-kotikov) [inline src/windows/BarcodeScannerProxy.js]: Same here - see previous commens

File: src/windows/BarcodeScannerProxy.js [hunk 3]
```diff
@@ -457,9 +475,20 @@ module.exports = {
...
+
+            if (error.message == 'Canceled') {
+                success({
+                    cancelled: true
+                });
+            } else {
+                fail(error);
+            }
+
+            BarcodeReader.scanCancelled = false;
```
Comment (vladimir-kotikov) [inline src/windows/BarcodeScannerProxy.js]: Ditto

**Comment by daserge** [comment]
@vladimir-kotikov, addressed, thanks for review!
