### PR TITLE
Scanning crashes on Windows phone on device rotation, this fixes #213

### LINKED ISSUE #172: Cannot scan in portrait mode on Win10 after fix for #155
This change:
Fixes Windows Mobile - Issue with Orientation
#155 
rotates only encoding preview.

Barcode still needs to be in landscape to be successfully scanned.
This version of ZXing library doesn't scan in both directions or at least this is what I get.

### LINKED ISSUE #202: Scanning with vertical mode on Win 10 Mobile not working [2]
Tested on Nokia Lumia 730 Windows 10 Mobile, horizontal works ok, vertical doesn't work. Maybe it has to do with screen size since a guy around here said it worked for a Lumia 720 with Win 10 mobile.

Please check.

### LINKED ISSUE #213: Scanning crashes on Windows phone on device rotation
When I am in the scanner and try to rotate the screen on a Windows 8.1 device, the application crashes with this message:

Unhandled exception at line 247, column 13 in ms-appx://com.blah.blah/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js

0xc00dabea - JavaScript runtime error: A property cannot be set because a photo or photo sequence is in progress.

A property cannot be set because a photo or photo sequence is in progress.

WinRT information: A property cannot be set because a photo or photo sequence is in progress.

### PR DESCRIPTION
**Pull request by daserge**
Fixes scanning in portrait orientation, this fixes #172, this fixes #202

### CODE REVIEW

File: src/windows/BarcodeScannerProxy.js [hunk 1]
```diff
@@ -243,7 +246,19 @@ module.exports = {
             // rotate the preview video
             var videoEncodingProperties = capture.videoDeviceController.getMediaStreamProperties(Windows.Media.Capture.MediaStreamType.videoPreview);
             videoEncodingProperties.properties.insert(ROTATION_KEY, rotDegree);
-            return capture.videoDeviceController.setMediaStreamPropertiesAsync(Windows.Media.Capture.MediaStreamType.videoPreview, videoEncodingProperties);
+
+            try {
+                return capture.videoDeviceController.setMediaStreamPropertiesAsync(Windows.Media.Capture.MediaStreamType.videoPreview, videoEncodingProperties);
+            } catch (e) {
+                if (e.number !== PHOTO_SEQUENCE_IS_IN_PROGRESS) {
```
Comment (vladimir-kotikov) [inline src/windows/BarcodeScannerProxy.js]: Could you add a comment clarifying why we can safely ignore this error?

File: src/windows/BarcodeScannerProxy.js [hunk 2]
```diff
@@ -243,7 +246,19 @@ module.exports = {
...
+                    throw e;
```
Comment (vladimir-kotikov) [inline src/windows/BarcodeScannerProxy.js]: Since `updatePreviewForRotation` is returning promise, wouldn't it be better to reject the resultant promise rather that throw synchronous exception?

File: src/windows/BarcodeScannerProxy.js [hunk 3]
```diff
@@ -243,7 +246,19 @@ module.exports = {
...
+                } else { // Retry:
```
Comment (vladimir-kotikov) [inline src/windows/BarcodeScannerProxy.js]: nit: `else` statement is excess here

File: src/windows/BarcodeScannerProxy.js (hunk 2 above)
Comment (daserge) [inline src/windows/BarcodeScannerProxy.js]: There is no intermediate promise variable - so could you please explain how can we reject a returned promise?
I believe it's ok to throw an exception as it will be caught in the topmost promise chain' done.

File: src/windows/BarcodeScannerProxy.js (hunk 1 above)
Comment (daserge) [inline src/windows/BarcodeScannerProxy.js]: This error is not documented anywhere, I can just assume that we can't apply MediaStreamProperties while a photo sequence is in progress - but the error constant name says this for itself.

File: src/windows/BarcodeScannerProxy.js (hunk 2 above)
Comment (vladimir-kotikov) [inline src/windows/BarcodeScannerProxy.js]: > ok to throw an exception as it will be caught in the topmost promise

Yeah, i noticed that. It is more like a good pattern to follow - function should return both success and error consistently - either in sync or async way.

**Comment by vladimir-kotikov** [comment]
@daserge, could you please also rebase this

**Comment by daserge** [comment]
Reworked and rebased, @vladimir-kotikov could you please take a look once more?
Scanning in portrait mode now works although the preview is being shrinked in this orientation.

**Comment by vladimir-kotikov** [comment]
Thanks, @daserge. I'll verify this on my devices and merge if everything is good

**Comment by vladimir-kotikov** [comment]
Tested on Lumia 730 w/ Windows 10 and Lumia 822 - everything seems to be working
