### PR TITLE
Catch Class not registered exception in case of missing Media Player/…

### LINKED ISSUE #367: Win 10 Pro N + Logitech c920 webcam = 0x80040154 - Class not registered
### Expected Behaviour
Using phonegap-plugin-barcode scanner master branch, Win 10 x86 laptop with Logitech c920 web cam, expected to be able to scan barcode value using example code on main project page. Project does not say that Win10 + web cam are not usable combination with this plugin, therefore I expected the plugin to scan a barcode.

Not sure what I'm doing wrong, since I'm new to this.

### Actual Behaviour
Received Visual Studio debugger error for 'Class not registered':

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception is about to be caught by JavaScript library code at line 444, column 17 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x80040154 - JavaScript runtime error: Class not registered

Exception is about to be caught by JavaScript library code at line 538, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pause'

Line 444 in master branch references the Windows.Media object:

var captureSettings = new Windows.Media.Capture.MediaCaptureInitializationSettings();

So, I'm not sure if my laptop is missing essential software that the plugin requires, or what. Looked on MSDN's site for this object, but it never stated how to get it, if it's missing or not registered.

[https://msdn.microsoft.com/library/windows/apps/windows.media.capture.mediacaptureinitializationsettings]

### Reproduce Scenario (including but not limited to)
(see Steps to Reproduce)

#### Steps to Reproduce
Win 10 + web cam with proper drivers, Cordova, Git and example project setup.

cordova build

Open Windows 10 Visual Studio project "platforms \ windows \ CordovaApp.vs2013.sln", modified package.windows10.appxmanifest Capabilities to include "Webcam" support (assumed that it's needed, but error occurs either way), then start debugger.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Microsoft Windows 10 Pro N, x86 arch   v. 10.0.14393 Build 14393
Microsoft Visual Studio Community 2015  v. 14.0.25425.01 Update 3
Microsoft .NET Framework v. 4.6.01586

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version

    cordova --version
            = 6.4.0

    cordova platforms
         = Installed platforms:
                     android 6.0.0
                     browser 4.1.0
                     windows 4.4.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

= phonegap-plugin-barcodescanner 6.0.3 "BarcodeScanner"

#### Sample Code that illustrates the problem
Example code from the project's main page..

cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      },
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          "preferFrontCamera" : true, // iOS and Android
          "showFlipCameraButton" : true, // iOS and Android
          "prompt" : "Place a barcode inside the scan area", // supported on Android only
          "formats" : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          "orientation" : "landscape" // Android only (portrait|landscape), default unset so it rotates with the device
      }
   );

#### Logs taken while reproducing problem

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception is about to be caught by JavaScript library code at line 444, column 17 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x80040154 - JavaScript runtime error: Class not registered

Exception is about to be caught by JavaScript library code at line 538, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pause'

### PR DESCRIPTION
**Pull request by daserge**
…Media Features

Updated the docs accordingly

This fixes #367

### CODE REVIEW

File: src/windows/BarcodeScannerProxy.js [hunk 1]
```diff
@@ -440,7 +441,20 @@ module.exports = {
         function startPreview() {
             return findCamera()
             .then(function (id) {
-                var captureSettings = new Windows.Media.Capture.MediaCaptureInitializationSettings();
+                var captureSettings;
+
+                try {
+                    captureSettings = new Windows.Media.Capture.MediaCaptureInitializationSettings();
+                } catch (e) {
+                    console.error(e);
```
Comment (vladimir-kotikov) [inline src/windows/BarcodeScannerProxy.js]: I'd remove the logging here - the error object will be available in error handler anyway.

Comment (daserge) [inline src/windows/BarcodeScannerProxy.js]: Addressed, thanks!

**Comment by vladimir-kotikov** [comment]
LGTM
